Models/ErrorViewModel.cs
namespace Market.Asp.Net.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Market.Asp.Net.Controllers
{
	public class AboutController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

Controllers/AdminController.cs
using Business.Abstract;
using DTO.EntityDTO;
using Microsoft.AspNetCore.Mvc;

namespace Market.Asp.Net.Controllers
{
	public class AdminController : Controller
	{
		private readonly ICategory _category;
		private readonly IProduct _product;
		private readonly ILogin _login;
		private readonly IRole _role;
		private readonly IMessage _message;
        public AdminController(ICategory category, IProduct product, ILogin login, IRole role,IMessage message)
        {
            _category = category;
            _product = product;
            _login = login;
            _role = role;
			_message = message;
        }






        #region Categories

        public IActionResult Index()
		{
			var values = _category.GetAll();
			return View(values);
		}
		[HttpGet]
		public IActionResult CategoryAdd()
		{
			
			return View();
		}
		[HttpPost]
		public IActionResult CategoryAdd(CategoryDTO category)
		{
			_category.Insert(category);
			return RedirectToAction("Index");
		}
		public IActionResult CategoryDelete(int id)
		{
			_category.Delete(id);
			return RedirectToAction("Index");
		}
        #endregion

        #region Products

		public IActionResult Product()
		{
			var values=_product.GetAllCategory();
			return View(values);
		}
        public IActionResult ProductDelete(int id)
        {
            _product.Delete(id);
            return RedirectToAction("Product");
        }
        [HttpGet]
		public IActionResult ProductAdd(int id)
		{
			ViewBag.ctg = _category.GetAll();
            return View();
		}
		[HttpPost]
		public IActionResult ProductAdd(ProductDTO product)
		{
			
			_product.Insert(product);
			return RedirectToAction("Product");
		}

		[HttpGet]
        public IActionResult ProductUpdate(int id)
        {
            ViewBag.ctg = _category.GetAll();
            var values=_product.GetByID(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult ProductUpdate(ProductDTO product)
        {
        
            _product.Update(product);
            return RedirectToAction("Product");
        }



		#endregion

		#region AdminLogin

		public IActionResult Users()
		{
			var values=_login.GetAllRole();
			return View(values);
		}

        public IActionResult UsersDelete(int id)
        {
           _login.Delete(id);
            return RedirectToAction("Users");
        }
		[HttpGet]
		public IActionResult UsersUpdate(int id)
		{
			ViewBag.status = _role.GetAll();
			var values=_login.GetByID(id);
			return View(values);
		}
		[HttpPost]
        public IActionResult UsersUpdate(LoginDTO dto)
        {
            _login.Update(dto);
            return RedirectToAction("Users");
        }



        [HttpGet]
        public IActionResult AdminRegister()
        {
			ViewBag.user = _role.GetAll();
            return View();
        }

		[HttpPost]
        public IActionResult AdminRegister(LoginDTO dto)
        {
			_login.Insert(dto);
            return RedirectToAction("Users");
        }


        #endregion

        #region Admin Review
		public IActionResult AdminReview()
		{
			var values=_message.GetAll();
			return View(values);
		}
		public IActionResult AdminReviewDelete(int id)
		{
			_message.Delete(id);
			return RedirectToAction("AdminReview");
		}
		[HttpGet]
		public IActionResult AdminReviewUpdate(int id)
		{
			var values=_message.GetByID(id);
			return View(values);
		}
		public IActionResult AdminReviewUpdate(MessageDTO dto)
		{
			_message.Update(dto);
			return RedirectToAction("AdminReview");
		}

		#endregion
	}
}

Controllers/ContactController.cs
using Business.Abstract;
using DTO.EntityDTO;
using Microsoft.AspNetCore.Mvc;

namespace Market.Asp.Net.Controllers
{
	public class ContactController : Controller
	{
		private readonly IMessage _message;

		public ContactController(IMessage message)
		{
			_message = message;
		}

		[HttpGet]
		public IActionResult Index()
		{

			return View();
		}

		[HttpPost]
		public IActionResult Index(MessageDTO dto)
		{
			_message.Insert(dto);


			return View();
		}
	}
}

Controllers/HomeController.cs
using Business.Abstract;
using DataAccess.MyContext;
using Market.Asp.Net.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Market.Asp.Net.Controllers
{
    public class HomeController : Controller
    {
        private readonly IProduct _product;
        private readonly ICategory _category;
        private readonly AppDbContext _context;

        public HomeController(IProduct product, ICategory category, AppDbContext context)
        {
            _product = product;
            _category = category;
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.c = _product.GetAll().Where(x => x.CategoryID == 2);
            var values = _product.GetAll();
            return View(values);
        }
        [HttpGet]
        public IActionResult Page(int id)
        {
            var values = _product.GetAllCategory(id);          
            return View(values);
        }
    
        public IActionResult Search(string search)
        {
            var values=from x in _product.GetAllCategory() select x;
            if (!string.IsNullOrEmpty(search))
            {
                values=values.Where(x=>x.Name.ToLower().Contains(search.ToLower()));
            }
            return View(values);
        }
    }
}

Controllers/LoginController.cs
using Business.Abstract;
using DataAccess.MyContext;
using DTO.EntityDTO;
using Microsoft.AspNetCore.Mvc;

namespace Market.Asp.Net.Controllers
{
	public class LoginController : Controller
	{
		private readonly ILogin _login;
		private readonly AppDbContext _context;

		public LoginController(ILogin login, AppDbContext context)
		{
			_login = login;
			_context = context;
		}

		public IActionResult Index(string username,string password)
		{
			var values=_login.GetAll().Where(x=>x.Username == username && x.Password==password).ToList().FirstOrDefault();
			if (values!=null && values.RoleId==1)
			{				
				return RedirectToAction("Index","Admin");
			}
			else if(values!=null && values.RoleId==3)
			{
				return RedirectToAction("Index","Home");
			}
			return View();
		}
	}
}

Controllers/RegisterController.cs
using Business.Abstract;
using DTO.EntityDTO;
using Microsoft.AspNetCore.Mvc;

namespace Market.Asp.Net.Controllers
{
    public class RegisterController : Controller
    {
        private readonly ILogin _login;
        private readonly IRole _role;

		public RegisterController(ILogin login, IRole role)
		{
			_login = login;
			_role = role;
		}
		[HttpGet]
		public IActionResult Index()
		{
			
			return View();
		}

		[HttpPost]
		public IActionResult Index(LoginDTO dto)
        {
			dto.RoleId = 3;
            _login.Insert(dto);
            return RedirectToAction("Index");
        }
    }
}

Controllers/ReviewController.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace Market.Asp.Net.Controllers
{
	public class ReviewController : Controller
	{
		private readonly IMessage _message;

		public ReviewController(IMessage message)
		{
			_message = message;
		}

		[HttpGet]
		public IActionResult Index()
		{
			var values = _message.GetAll();
			return View(values);
		}
	}
}

Views/About/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}


<body>
	<!-- about -->
	<div class="about">
		<div class="container">
			<h3 class="w3_agile_header">Haqqımızda</h3>
			<div class="about-agileinfo w3layouts">
				<div class="col-md-8 about-wthree-grids grid-top">
					<h4>Blanditiis praesentium deleniti atque corrupti quos </h4>
					<p class="top">Gnissimos voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi. atque corrupti quos dolores et quas molestias excepturi sint occaecat officia deserunt mollitia laborum et dolorum fuga</p>
					<p>Dignissimos at vero eos et accusamus et iusto odio ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecat officia deserunt mollitia laborum et dolorum fuga. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecat atque corrupti quos dolores et quas molestias excepturi sint occaecat officia deserunt mollitia laborum et dolorum </p>
					<div class="about-w3agilerow">
						<div class="col-md-4 about-w3imgs">
							<img src="~/web/images/p3.jpg" alt="" class="img-responsive zoom-img" />
						</div>
						<div class="col-md-4 about-w3imgs">
							<img src="~/web/images/p4.jpg" alt="" class="img-responsive zoom-img" />
						</div>
						<div class="col-md-4 about-w3imgs">
							<img src="~/web/images/p3.jpg" alt="" class="img-responsive zoom-img" />
						</div>
						<div class="clearfix"> </div>
					</div>
				</div>
				<div class="col-md-4 about-wthree-grids">
					<div class="offic-time">
						<div class="time-top">
							<h4>Praesentium :</h4>
						</div>
						<div class="time-bottom">
							<h5>At vero eos </h5>
							<h5>Accusamus et</h5>
							<p>Dignissimos at vero eos et accusamus et iusto odio ducimus qui accusamus et. </p>
						</div>
					</div>
					<div class="testi">
						<h3 class="w3_agile_header">Testimonial</h3>
						<!--//End-slider-script -->
						<script src="~/web/js/responsiveslides.min.js"></script>
						<script>
							// You can also use "$(window).load(function() {"
							$(function () {
							  // Slideshow 5
							  $("#slider5").responsiveSlides({
								auto: true,
								pager: false,
								nav: true,
								speed: 500,
								namespace: "callbacks",
								before: function () {
								  $('.events').append("<li>before event fired.</li>");
								},
								after: function () {
								  $('.events').append("<li>after event fired.</li>");
								}
							  });

							});
						</script>
						<div id="top" class="callbacks_container">
							<ul class="rslides" id="slider5">
								<li>
									<div class="testi-slider">
										<h4>" I AM VERY PLEASED.</h4>
										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eu magna dolor, quisque semper.</p>
										<div class="testi-subscript">
											<p><a href="#">John Doe,</a>Adipiscing</p>
											<span class="w3-agilesub"> </span>
										</div>
									</div>
								</li>
								<li>
									<div class="testi-slider">
										<h4>" I AM LOREM IPSUM.</h4>
										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eu magna dolor, quisque semper.</p>
										<div class="testi-subscript">
											<p><a href="#">elit semper,</a>Dolor Elit</p>
											<span class="w3-agilesub"> </span>
										</div>
									</div>
								</li>
								<li>
									<div class="testi-slider">
										<h4>" CONSECTETUR PIMAGNA.</h4>
										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eu magna dolor, quisque semper.</p>
										<div class="testi-subscript">
											<p><a href="#">Amet Doe,</a>Suspendisse</p>
											<span class="w3-agilesub"> </span>
										</div>
									</div>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //about -->
	<!-- about-slid -->
	<div class="about-slid agileits-w3layouts">
		<div class="container">
			<div class="about-slid-info">
				<h2>Lorem Ipsum is that it has a moreless normal</h2>
				<p>Lorem Ipsum generators on the Internet tend to repeat predefined chunks on the Internet tend as necessary, making this the first true generator on the Internet embarrassing hidden in the middle of text Lorem Ipsum generators on the Internet tend to repeat predefinedchunks as necessary, making this the first true generator on the.</p>
			</div>
		</div>
	</div>
	<!-- //about-slid -->
	<!-- about-team -->
	<div class="about-team">
		<div class="container">
			<h3 class="w3_agile_header">Meet Our Team</h3>
			<div class="team-agileitsinfo">
				<div class="col-md-3 about-team-grids">
					<img src="~/web/images/t4.jpg" alt="" />
					<div class="team-w3lstext">
						<h4><span>ANDERSON,</span> Manager</h4>
						<p>Odio dignissimos vero eos voluptatem accusantium doloremque laudantium reader will be distracted.</p>
					</div>
					<div class="social-icons caption">
						<ul>
							<li><a href="#" class="fa fa-facebook facebook"> </a></li>
							<li><a href="#" class="fa fa-twitter twitter"> </a></li>
							<li><a href="#" class="fa fa-google-plus googleplus"> </a></li>
						</ul>
						<div class="clearfix"> </div>
					</div>
				</div>
				<div class=" col-md-3 about-team-grids">
					<img src="~/web/images/t2.jpg" alt="" />
					<div class="team-w3lstext">
						<h4><span>ELIFS,</span> Director</h4>
						<p>Odio dignissimos vero eos voluptatem accusantium doloremque laudantium reader will be distracted.</p>
					</div>
					<div class="social-icons caption">
						<ul>
							<li><a href="#" class="fa fa-facebook facebook"> </a></li>
							<li><a href="#" class="fa fa-twitter twitter"> </a></li>
							<li><a href="#" class="fa fa-google-plus googleplus"> </a></li>
						</ul>
						<div class="clearfix"> </div>
					</div>
				</div>
				<div class="col-md-3 about-team-grids">
					<img src="~/web/images/t1.jpg" alt="" />
					<div class="team-w3lstext">
						<h4><span>JESSICA,</span> Supervisior</h4>
						<p>Odio dignissimos vero eos voluptatem accusantium doloremque laudantium reader will be distracted.</p>
					</div>
					<div class="social-icons caption">
						<ul>
							<li><a href="#" class="fa fa-facebook facebook"> </a></li>
							<li><a href="#" class="fa fa-twitter twitter"> </a></li>
							<li><a href="#" class="fa fa-google-plus googleplus"> </a></li>
						</ul>
						<div class="clearfix"> </div>
					</div>
				</div>
				<div class="col-md-3 about-team-grids">
					<img src="~/web/images/t3.jpg" alt="" />
					<div class="team-w3lstext">
						<h4><span>RACKHAM,</span> Staff</h4>
						<p>Odio dignissimos vero eos voluptatem accusantium doloremque laudantium reader will be distracted.</p>
					</div>
					<div class="social-icons caption">
						<ul>
							<li><a href="#" class="fa fa-facebook facebook"> </a></li>
							<li><a href="#" class="fa fa-twitter twitter"> </a></li>
							<li><a href="#" class="fa fa-google-plus googleplus"> </a></li>
						</ul>
						<div class="clearfix"> </div>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //about-team -->

</body>

Views/Admin/AdminRegister.cshtml
@model DTO.EntityDTO.LoginDTO
@{
    ViewData["Title"] = "AdminRegister";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<div class="register">
    <div class="container">
        <h2>Qeydiyyat</h2>
        <div class="login-form-grids">
            <form method="post">
                <input type="text" asp-for="Username" placeholder="İstifadəçi adı" required=" ">
                <input type="password" asp-for="Password" placeholder="Şifrə" required=" ">
                <br />
                <select asp-for="RoleId">
                    @foreach (var item in ViewBag.user)
                    {
                        <option value="@item.Id">@item.Status </option>
                    }
                </select>
                <input type="submit" value="Qeydiyyatdan kec">
            </form>
        </div>
        <div class="register-home">
            <a asp-controller="Admin" asp-action="Index">Admin Panel</a>
        </div>
    </div>
</div>

Views/Admin/AdminReview.cshtml
@model IEnumerable<DTO.EntityDTO.MessageDTO>
@{
    ViewData["Title"] = "AdminReview";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="table-heading">
	<h2>Rəylər</h2>
</div>
<div class="agile-tables">
	<div class="w3l-table-info">	
		<table id="table">
			<thead>
				<tr>
					<th>#</th>
					<th>Adi</th>
					<th>Mesaj</th>
					<th>Redaktə et</th>
					<th>Sil</th>

				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td>@item.Id</td>
						<td>@item.Name</td>
						<td>@item.Description</td>
						<td>
							<a asp-controller="Admin" asp-action="AdminReviewUpdate" asp-route-id="@item.Id"
							   class="btn btn-primary" style="background-color:green">
								Redaktə et
							</a>
						</td>
						<td>
							<a asp-controller="Admin" asp-action="AdminReviewDelete" asp-route-id="@item.Id"
							   class="btn btn-warning" style="background-color:red">
								Sil
							</a>
						</td>


					</tr>
				}
			</tbody>
		</table>
	</div>

Views/Admin/AdminReviewUpdate.cshtml
@model DTO.EntityDTO.MessageDTO
@{
    ViewData["Title"] = "AdminReviewUpdate";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<form asp-route-id="@Model.Id" method="post">
    <span class="input input--ichiro">
        <span class="input__label-content input__label-content--ichiro" style="font-size:large">Adı</span>
        <br />
        <input class="input__field input__field--ichiro" type="text" id="input-25" name="Name" required="" value="@Model.Name" />
        <label class="input__label input__label--ichiro" for="input-25">
        </label>
        <br />
    </span>
    <br />
    <span>

        <span class="input__label-content input__label-content--ichiro" style="font-size:large">Mesaj</span>

        <textarea name="Description" required="">@Model.Description </textarea>
    </span>
    <input type="submit" value="Redaktə et">


</form>

Views/Admin/CategoryAdd.cshtml
@model DTO.EntityDTO.CategoryDTO

@{
    ViewData["Title"] = "CategoryAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="agile-grids">
    <!-- input-forms -->
    <div class="grids">
        <div class="progressbar-heading grids-heading">
            <h2>Kateqoriya Formu</h2>
        </div>
        <div class="panel panel-widget forms-panel">
            <div class="forms">
                <div class="form-grids widget-shadow" data-example-id="basic-forms">
                    <div class="form-title">
                    </div>
                    <div class="form-body">
                        <form  method="post">
                            <div class="form-group">
                                <label for="exampleInputFile">Kateqoriya adi</label>
                                <input type="text" asp-for="Name" class="form-control" id="exampleInputFile">
                            </div>

                            <button type="submit" class="btn btn-primary w3ls-button">Elave et</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- //input-forms -->
    </div>
</div>
   

Views/Admin/Index.cshtml
@model IEnumerable<DTO.EntityDTO.CategoryDTO>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="table-heading">
	<h2>Kateqoriyalar</h2>
</div>
<div class="agile-tables" >
	<div class="w3l-table-info">
		<h3>Kateqoriyalar</h3>
	<a asp-controller="Admin" asp-action="CategoryAdd" class="btn btn-primary"  >
		+ Yeni
	</a>
		<table id="table">
			<thead>
				<tr>
					<th>#</th>
					<th>Adi</th>
					<th>Sil</th>

				</tr>
			</thead>
			<tbody>
				@foreach(var item in Model)
				{
					<tr>
						<td>@item.Id</td>
						<td>@item.Name</td>
						<td> <a asp-controller="Admin" asp-action="CategoryDelete" asp-route-id="@item.Id" 
						class="btn btn-warning" style="background-color:red">
								Sil
						</a> </td>


					</tr>
				}
			</tbody>
		</table>
	</div>

Views/Admin/Product.cshtml
@model IEnumerable<DTO.EntityDTO.ProductDTO>
@{
    ViewData["Title"] = "Product";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="table-heading">
    <h2>Produktlar</h2>
</div>
<div class="agile-tables">
    <div class="w3l-table-info">

        <a asp-controller="Admin" asp-action="ProductAdd" class="btn btn-primary">
            + Yeni
        </a>
        <table id="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Kateqoriyası</th>
                    <th>Adi</th>
                    <th>Qiyməti</th>
                    <th>Endirimli qiyməti</th>
                    <th>Say</th>
                    <th>Şəkil</th>
                    <th>Redaktə et</th>
                    <th>Sil</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.CategoryName</td>
                        <td>@item.Name</td>
                        <td>@item.Price</td>
                        <td>@item.DisCount</td>
                        <td>@item.Quantity</td>
                        <td>@item.Image</td>
                        <td>

                            <a asp-controller="Admin" asp-action="ProductUpdate" asp-route-id="@item.Id"
                               class="btn btn-primary" style="background-color:forestgreen">
                                Redaktə et
                            </a>
                        </td>

                        <td>
                            <a asp-controller="Admin" asp-action="ProductDelete" asp-route-id="@item.Id"
                               class="btn btn-warning" style="background-color:red">
                                Sil
                            </a>
                        </td>


                    </tr>
                }
            </tbody>
        </table>
    </div>

Views/Admin/Users.cshtml
@model IEnumerable<DTO.EntityDTO.LoginDTO>
@{
    ViewData["Title"] = "Users";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="table-heading">
    <h2>İstifadəçilər</h2>
</div>
<div class="agile-tables">
    <div class="w3l-table-info">

        <a asp-controller="Admin" asp-action="AdminRegister" class="btn btn-primary">
            + Yeni
        </a>
        <table id="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>İstifadəçi adı</th>
                    <th>Şifrəsi</th>
                    <th>Statusu</th>           
                    <th>Redaktə et</th>
                    <th>Sil</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Username</td>
                        <td>@item.Password</td>
                        <td>@item.RoleName</td>
                  
                        <td>

                            <a asp-controller="Admin" asp-action="UsersUpdate" asp-route-id="@item.Id"
                               class="btn btn-primary" style="background-color:forestgreen">
                                Redaktə et
                            </a>
                        </td>

                        <td>
                            <a asp-controller="Admin" asp-action="UsersDelete" asp-route-id="@item.Id"
                               class="btn btn-warning" style="background-color:red">
                                Sil
                            </a>
                        </td>


                    </tr>
                }
            </tbody>
        </table>
    </div>

Views/Partials/_Footer.cshtml
<div class="footer">
	<div class="container">
		<div class="w3_footer_grids">
			<div class="col-md-3 w3_footer_grid">
				<h3>Contact</h3>

				<ul class="address">
					<li><i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i>1234k Avenue, 4th block, <span>Baku</span></li>
					<li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="mailto:info@example.com">info@example.com</a></li>
					<li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>+1234 567 567</li>
				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3>Information</h3>
				<ul class="info">
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a asp-controller="About" asp-action="Index" >Haqqımızda</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a asp-controller="Contact" asp-action="Index">Bizimlə əlaqə</a></li>
				</ul>
			</div>
			@await Component.InvokeAsync("FooterList")
			<div class="col-md-3 w3_footer_grid">
				<h3>Profile</h3>
				<ul class="info">	
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a asp-controller="Login" asp-action="Index">Login</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a asp-controller="Register" asp-action="Index">Qeydiyyat</a></li>
				</ul>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>

	<div class="footer-copy">

		<div class="container">
			<p>© 2024 Super Market. All rights reserved | Design by <a href="http://w3layouts.com/">Kamil Rustemli</a></p>
		</div>
	</div>

</div>

Views/Partials/_Header.cshtml
<div class="agileits_header">
	<div class="container">
		<div class="w3l_offers">
			<p>SALE UP TO 70% OFF. USE CODE "SALE70%" . <a href="products.html">SHOP NOW</a></p>
		</div>
		<div class="agile-login">
			<ul>
				<li><a asp-controller="Register" asp-action="Index"> Create Account </a></li>
				<li><a asp-controller="Login" asp-action="Index">Login</a></li>
				

			</ul>
		</div>
		<div class="product_list_header">
			<form action="#" method="post" class="last">
				<input type="hidden" name="cmd" value="_cart">
				<input type="hidden" name="display" value="1">
				<button class="w3view-cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
			</form>
		</div>
		<div class="clearfix"> </div>
	</div>
</div>

<div class="logo_products">
	<div class="container">
		<div class="w3ls_logo_products_left1">
			<ul class="phone_email">
				<li><i class="fa fa-phone" aria-hidden="true"></i>Bizimlə əlaqə : (012) 199</li>

			</ul>
		</div>
		<div class="w3ls_logo_products_left">
			<h1><a asp-controller="Home" asp-action="Index">Super Market</a></h1>
		</div>
		<div class="w3l_search">
			<form asp-controller="Home" asp-action="Search" name="search" method="get">
				<input type="search" name="search" placeholder="Axtarış" required="">
				<button type="submit" class="btn btn-default search" aria-label="Left Align">
					<i class="fa fa-search" aria-hidden="true"> </i>
				</button>
				<div class="clearfix"></div>
			</form>
		</div>

		<div class="clearfix"> </div>
	</div>
</div>

Views/Partials/_NavBar.cshtml
@await Component.InvokeAsync("CategoryList")

Views/Shared/Components/CategoryList/Default.cshtml
@model IEnumerable< DTO.EntityDTO.CategoryDTO>


<div class="navigation-agileits">
    <div class="container">
        <nav class="navbar navbar-default">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header nav_2">
                <button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
                <ul class="nav navbar-nav">
                    <li class="active"><a asp-controller="Home" asp-action="Index" class="act">Əsas Səhifə</a></li>
                    @foreach (var item in Model)
                    {
                        <li><a asp-controller="Home" asp-action="Page" asp-route-id="@item.Id">@item.Name</a></li>
                    }

                    <li class="active"><a asp-controller="About" asp-action="Index" class="act">Haqqımızda</a></li>
                    <li class="active"><a asp-controller="Contact" asp-action="Index" class="act">Bizimlə əlaqə</a></li>
                    <li class="active"><a asp-controller="Review" asp-action="Index" class="act">Rəylər</a></li>

                    <li class="active"><a asp-controller="Admin" asp-action="Index" class="act">Admin</a></li>


                </ul>
            </div>
        </nav>
    </div>
</div>

Views/Shared/Components/FooterList/Default.cshtml
@model IEnumerable<DTO.EntityDTO.CategoryDTO>

<div class="col-md-3 w3_footer_grid">
	<h3>Kateqoriya</h3>
	<ul class="info">
		@foreach(var item in Model)
		{ 
			<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a asp-controller="Home" asp-action="Page" asp-route-id="@item.Id">@item.Name</a></li>
		}
	</ul>
</div>